---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/rewards/import":
    post:
      summary: import reward
      tags:
      - Rewards
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              example:
                A: 1.75
                B: 1.5
                C: 1
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
        required: true
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
